language: go

go:
  - 1.0
  - 1.1
  - 1.2
  - tip

before_install:
  - go get -v code.google.com/p/go.tools/cmd/cover
  - go get -v code.google.com/p/go.tools/cmd/vet
  - go get -v github.com/golang/lint/golint
  - export PATH=$PATH:/home/travis/gopath/bin

script:
  - go test -v -cover ./...
  - go vet ./...
  - golint .
