## Copyright 2014~2019 Alvaro J. Genial. All rights reserved.
## Use of this source code is governed by a BSD-style
## license that can be found in the LICENSE file.

language: go

go:
  - master
  - tip
  - 1.9
  - 1.8
  - 1.7
  - 1.6
  - 1.5
  - 1.4
  - 1.3
  - 1.2

before_install:
  - go get -v golang.org/x/tools/cmd/cover  || echo 'could not get cover'
  - go get -v golang.org/x/tools/cmd/vet    || echo 'could not get vet'
  - go get -v golang.org/x/lint/golint      || echo 'could not get golint'
  - export PATH="$PATH:/home/travis/gopath/bin"

script:
  - go build -v ./...
  - if go tool cover -V; then go test -v -cover ./...; else echo 'no cover'; go test -v ./...; fi
  - if go tool vet   -V; then go vet  -v        ./...; else echo 'no vet';                     fi
  - if which golint;     then golint            ./...; else echo 'no golint';                  fi
